url: http://candycode.github.com
pygments: true
markdown: kramdown
server: true
project_title: Ugo's dusty attic
project_tagline: quaerendo invenietis
#project_tagline: ...
owner_name: candycode
title: Ugo's website
repository_url: http://github.com/candycode/candycode.github.com
zip_url: https://github.com/candycode/candycode.github.com/zipball/master
tar_url: https://github.com/candycode/candycode.github.com/tarball/master
owner_url: http://github.com/candycode
analytics: true
permalink: none
future: true
feedburner: false
contactform: true
