pygments: true
markdown: rdiscount
server: true
project_title: Ugo's dusty attic
owner_name: candycode
title: Ugo's website
repository_url: http://github.com/candycode/candycode.github.com
zip_url: https://github.com/candycode/candycode.github.com/zipball/master
tar_url: https://github.com/candycode/candycode.github.com/tarball/master
owner_url: http://github.com/candycode
